// Test script para verificar la creación automática de chats
// Ejecutar en la consola del navegador en http://localhost:3002

console.log('🧪 Iniciando test de creación automática de chats...');

// Función para simular una primera conversación
async function testAutoChatCreation() {
  console.log('1️⃣ Verificando estado inicial...');
  
  // Verificar si el usuario está autenticado
  const isAuthenticated = window.isAuthenticated || false;
  const userData = window.userData || null;
  const currentChatId = window.currentChatId || null;
  const messages = window.messages || [];
  
  console.log('Estado actual:', {
    isAuthenticated,
    userData: userData ? '✅ Usuario autenticado' : '❌ Usuario no autenticado',
    currentChatId,
    messagesLength: messages.length
  });
  
  if (!isAuthenticated) {
    console.log('❌ Usuario no autenticado. Por favor inicia sesión primero.');
    return;
  }
  
  // Verificar si es primera conversación
  const isFirstConversation = !currentChatId && messages.length === 0;
  console.log('¿Es primera conversación?', isFirstConversation);
  
  if (!isFirstConversation) {
    console.log('❌ No es primera conversación. Limpia el estado para probar.');
    return;
  }
  
  console.log('✅ Condiciones correctas para prueba de creación automática');
  console.log('📝 Ahora envía un mensaje para probar la funcionalidad...');
}

// Función para verificar el resultado
function checkAutoChatResult() {
  console.log('2️⃣ Verificando resultado de creación automática...');
  
  const chats = window.chats || [];
  const currentChatId = window.currentChatId || null;
  const isCreatingChat = window.isCreatingChat || false;
  
  console.log('Estado después del mensaje:', {
    chatsCount: chats.length,
    currentChatId,
    isCreatingChat,
    chats: chats.map(chat => ({
      id: chat.id,
      name: chat.name,
      isAutoGenerated: chat.isAutoGenerated
    }))
  });
  
  if (chats.length > 0) {
    const autoChat = chats.find(chat => chat.isAutoGenerated);
    if (autoChat) {
      console.log('✅ ¡ÉXITO! Chat creado automáticamente:', autoChat.name);
    } else {
      console.log('⚠️ Chat creado pero no marcado como auto-generado');
    }
  } else {
    console.log('❌ No se creó ningún chat automáticamente');
  }
}

// Función para limpiar estado y probar de nuevo
function resetForTest() {
  console.log('🔄 Limpiando estado para nueva prueba...');
  
  // Limpiar mensajes
  if (window.setMessages) {
    window.setMessages([]);
  }
  
  // Limpiar chat actual
  if (window.setCurrentChatId) {
    window.setCurrentChatId(null);
  }
  
  console.log('✅ Estado limpiado. Ahora puedes probar de nuevo.');
}

// Exportar funciones para uso en consola
window.testAutoChatCreation = testAutoChatCreation;
window.checkAutoChatResult = checkAutoChatResult;
window.resetForTest = resetForTest;

console.log('🧪 Test script cargado. Usa:');
console.log('  - testAutoChatCreation() para verificar estado inicial');
console.log('  - checkAutoChatResult() para verificar resultado');
console.log('  - resetForTest() para limpiar estado y probar de nuevo'); 